language: java
sudo: true
script: mvn clean verify -Dmaven.test.redirectTestOutputToFile=true

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

jdk:
  - oraclejdk8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3
