language: java
sudo: true
script: mvn clean verify -Dmaven.test.redirectTestOutputToFile=true

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

jdk:
  - oraclejdk8
