language: java
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script: mvn clean verify -Dmaven.test.redirectTestOutputToFile=true

jdk:
  - oraclejdk8
